export const GMAIL_SYNC_MAX_RESULTS = 20;

export const GMAIL_ERRORS = {
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_NOT_FOUND: "EMAIL_NOT_FOUND",
  SYNC_FAILED: "SYNC_FAILED",
  FETCH_FAILED: "FETCH_FAILED",
} as const;

export const GMAIL_DEFAULT_LIST_LIMIT = 20;
export const GMAIL_MAX_LIST_LIMIT = 100;
