export const CALENDAR_SYNC_MAX_RESULTS = 50;

export const CALENDAR_ERRORS = {
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EVENT_NOT_FOUND: "EVENT_NOT_FOUND",
  SYNC_FAILED: "SYNC_FAILED",
  FETCH_FAILED: "FETCH_FAILED",
  CREATE_FAILED: "CREATE_FAILED",
} as const;

export const CALENDAR_DEFAULT_LIST_LIMIT = 20;
export const CALENDAR_MAX_LIST_LIMIT = 100;
