export const TASK_ERRORS = {
  USER_NOT_FOUND: "USER_NOT_FOUND",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  FETCH_FAILED: "FETCH_FAILED",
  CREATE_FAILED: "CREATE_FAILED",
  UPDATE_FAILED: "UPDATE_FAILED",
  DELETE_FAILED: "DELETE_FAILED",
} as const;

export const TASK_DEFAULT_LIST_LIMIT = 50;
